### ISSUE TITLE
How to dump the Yaml data loaded with your parser?

### ISSUE THREAD

**Issue by vasiqmz** [ChloeTigre/pyyaml-keep-anchors#1]
I was wondering, if there's a way to dump the data and also resolve the anchors back the default values.
And by dumping the data, I mean writing the data back to a new file again.

I have tried using your parser to load the Yaml file and then use the yaml.dump to dump the data but then the data is messed up.

Any thoughts on this ?

**Comment by matchaxnb** [comment]
Hello :)

It's not been designed for this goal. I could do it but there would not be much sense to the generated file. Indeed, which is the original anchor position and which is the pointer?

It's not been designed with that in mind. The dumped format really sucks if you re-dump the yaml so I don't recommend using it for that.

**Comment by matchaxnb** [comment]
Use https://pypi.python.org/pypi/ruamel.yaml/ instead. It's much better and not a use-once hack.

**Comment by matchaxnb** [comment]
Source project is here: https://bitbucket.org/ruamel/yaml

**Comment by vasiqmz** [comment]
Hello ...
Ya I read your code, but then I wanted to see the feasibility of the feature if I can add that or not.
Anyways, I'll just use the Ruamel YAML.
Thanks.
